project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "BMSC 620: Introduction to Biostatistics"
  navbar:
    background: primary
    search: true
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: homework.qmd
        text: Homework
      - href: exams.qmd
        text: Exams
      - href: resources.qmd
        text: Resources

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: homework.qmd
        text: Homework
      - href: exams.qmd
        text: Exams
      - section: "Course info"
        contents:
          - href: syllabus.qmd
            text: Syllabus
          - href: instructors.qmd
            text: Instructors
          - href: resources.qmd
            text: Resources
      - section: "Weekly materials"
        # contents: weeks/week_*.qmd
        # contents: 
        #   - weeks/week_01.qmd
        contents:
          - href: weeks/week_01.qmd
            text: Week 1
          - href: weeks/week_02.qmd
            text: Week 2

execute:
  freeze: auto

format:
  html:
    theme: flatly
    css: assets/css/styles.css
    toc: true
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    fontsize: 1.05em


