project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "BMSC 620: Introduction to Biostatistics"
  navbar:
    background: primary
    search: true
    foreground: "#fff"
    collapse-below: sm
    right:
          - href: schedule.qmd
            text: Schedule
          - href: materials.qmd
            text: Materials
          - href: syllabus.qmd
            text: Syllabus
          - href: instructors.qmd
            text: Instructors
          - href: homework.qmd
            text: Homework
          - href: quiz.qmd
            text: Quizzes
            
execute:
  freeze: auto

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    fontsize: 1.05em



